INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('아이스 아메리카노', 3000);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('아이스 카페라떼', 4000);
INSERT INTO `coffee`.menu(`menu_name`, `menu_price`)
VALUES ('아이스 바닐라라떼', 4500);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 아메리카노', 2500);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 카페라떼', 3500);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 바닐라라떼', 4000);